apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: preethiagnes/app: T80dd8deb13f3868689a26bf4282419f26bb22c7d T13243dd973864239f94ad8550271b651e6f1abd3
          ports:
            - containerPort: 80  # Adjust the container port as needed
