apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: argocd
data:
  otel.yaml: |
    receivers:
      otlp:
        endpoint: "0.0.0.0:55680"
    processors:
      batch:
    exporters:
      otlp/argocd:
        endpoint: "argocd-opentelemetry-collector:55680"
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/argocd]
