apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: argocd
data:
  otel.yaml: |
    receivers:
      otlp:
        endpoint: "0.0.0.0:5555"
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: "http://localhost:16686"
        insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [logging]
        traces:
          receivers: [otlp]
          exporters: [logging, otlp]
      telemetry:
        logs:
          level: debug
