apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: argocd  # Use the appropriate namespace
spec:
  selector:
    app: otel-collector
  ports:
    - name: otel
      port: 55680
      targetPort: 4317  # The collector container's port
      env:
      - name: OTEL_CONFIG
        valueFrom:
          configMapKeyRef:
            name: otel-collector-config
            key: config.yaml
