apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: preethiagnes/ado:1d29510842265aef2e261797b1e773ca139f74cd
          ports:
            - containerPort: 80  # Adjust the container port as needed
