apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: preethiagnes/ado:20231026.1
          ports:
            - name: http-web-svc
              containerPort: 80
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector:4317"  # Use the service name and port of the collector
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          volumeMounts:
            - name: collector-config
              mountPath: /etc/collector
      volumes:
        - name: collector-config
          configMap:
            name: otel-collector-config
