apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: preethiagnes/ado:20231025.14
          ports:
            - name: http-web-svc  # Ensure this matches the name in your service
              containerPort: 80
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "argocd-opentelemetry-collector:55680"  # This should match your collector's service name and port

        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          resources:
           limits:
             cpu: '1'
             memory: 2Gi
           requests:
             cpu: 200m
             memory: 400Mi
         ports:
           - containerPort: 4317   #otlp grpc
           - containerPort: 4318   # otlp http
           - containerPort: 55679  # zpages
           - containerPort: 13133  # health check
          volumeMounts:
            - name: collector-config
              mountPath: /etc/collector
      volumes:
        - name: collector-config
          configMap:
            name: otel-collector-config # Name of the ConfigMap containing your collector configuration
