apiVersion: v1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: deployment
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
      otlp:
      jaeger:
        endpoint: "http://localhost:16686"
        tls: 
          insecure: "true"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [jaeger,otlp]
        metrics:
          receivers: [otlp]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          exporters: [otlp]
